spring.application.name=Takataka
spring.jpa.database=POSTGRESQL
<<<<<<< HEAD
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
=======
spring.datasource.url=jdbc:postgresql://localhost:5432/takataka
>>>>>>> 4d7eb6928356de21f8ce8d16429d66e87c791940
spring.datasource.username=postgres
spring.datasource.password=root
spring.mvc.hiddenmethod.filter.enabled=true